# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViewCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViewCode
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Alamofire', '~> 5.4'
pod 'SDWebImage', '~> 5.0'
pod 'SwiftLint'

target 'ViewCodeTests' do
  inherit! :search_paths
  pod 'SnapshotTesting', '~> 1.9.0'

  end
end
